# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests (End-to-End)

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "53 0 * * SAT" # Every Saturday at 00:53 UTC

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox
        run: pipx install tox
      - name: Run linters
        run: make lint

  e2e-tests:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        tox-environments:
          - integration-e2e-basic-flow
          # - integration-e2e-password-rotation
        tls:
          - false
          - true
        options:
          -
          - --integrator
        juju:
          # - snap_channel: "3.4/stable"
          #   agent: "3.4.2"
          - snap_channel: "3.6/stable"
            agent: "3.6.0"
    name: ${{ matrix.tox-environments }}_${{matrix.tls}}_${{ matrix.juju.agent || matrix.juju.snap_channel }}
    needs:
      - lint
    # runs-on: ["self-hosted", "linux", "X64", "jammy", "large"]
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: (GitHub hosted) Free up disk space
        timeout-minutes: 5
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /usr/share/dotnet
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: ${{ matrix.juju.snap_channel }}
          bootstrap-options: "--agent-version ${{ matrix.juju.agent }}"
          provider: microk8s
          channel: 1.28-strict/stable
          microk8s-group: snap_microk8s
          microk8s-addons: "hostpath-storage dns"
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration e2e tests
        run: |
          if [[ "${{ matrix.tls }}" == "true" ]]; then
            FLAGS="${{matrix.options}} --tls"
          else
            FLAGS="${{matrix.options}}"
          fi
          
          make build TLS=${{ matrix.tls }}
          echo "======================"
          echo "Bundle being deployed:"
          echo "======================"
          cat build/bundle.yaml
          echo "======================"
          tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}' $FLAGS